spring:
    datasource:
        name: animal_ai
        url: jdbc:mysql://139.199.66.249:3306/zhihu?useUnicode=true&characterEncoding=UTF-8
        username: zysung
        password: 160058
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 300
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
    redis:
      database: 0
      host: 139.199.66.249
      port: 6379
      password: 123456
      timeout: 0
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0




mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.zysung.entity